samplesheet: "tests/test_data/minimal-example/samplesheet.csv"
outdir: "out-minimal-dev"
#workflow_level: "sample,compare,patient" - uncomment once patient is fixed
workflow_level: "sample,compare"
input_format: "adaptive"
max_memory: 10.GB
max_cpus: 4